export default [
  {
    id: 1,
    name: "Chocolate Cake",
    price_amount: "1200",
    image: null,
    price_currency: "NGN",
    description: "Decadent chocolate cake.",
    price: "NGN1200",
    stock_uom: "Unit",
    available_stock_quantity: 10,
    barcode: "choco4567",
    userFav: true,
    userPined: false,
    valuation_rate: "1300",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "18",
    warehouse: "obigbp",
  },
  {
    id: 2,
    name: "Vanilla Ice Cream",
    price_amount: "8000",
    image: null,
    price_currency: "NGN",
    description: "Smooth vanilla ice cream.",
    price: "NGN8000",
    stock_uom: "Unit",
    available_stock_quantity: 15,
    barcode: "vanilla1234",
    userFav: false,
    userPined: true,
    valuation_rate: "850",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "10",
    warehouse: "obigbp",
  },
  {
    id: 3,
    name: "Blueberry Muffin",
    price_amount: "5000",
    image: null,
    price_currency: "NGN",
    description: "Freshly baked blueberry muffin.",
    price: "NGN5000",
    stock_uom: "Unit",
    available_stock_quantity: 20,
    barcode: "blue4567",
    userFav: true,
    userPined: false,
    valuation_rate: "550",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "12",
    warehouse: "obigbp",
  },
  {
    id: 4,
    name: "Cappuccino",
    price_amount: "6000",
    image: null,
    price_currency: "NGN",
    description: "Rich and frothy cappuccino.",
    price: "NGN6000",
    stock_uom: "Unit",
    available_stock_quantity: 30,
    barcode: "cappu7890",
    userFav: false,
    userPined: true,
    valuation_rate: "650",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "8",
    warehouse: "obigbp",
  },
  {
    id: 5,
    name: "Pepperoni Pizza",
    price_amount: "1800",
    image: null,
    price_currency: "NGN",
    description: "Delicious pepperoni pizza.",
    price: "NGN1800",
    stock_uom: "Unit",
    available_stock_quantity: 12,
    barcode: "pizza9876",
    userFav: true,
    userPined: false,
    valuation_rate: "1900",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "20",
    warehouse: "obigbp",
  },
  {
    id: 6,
    name: "Mango Smoothie",
    price_amount: "7000",
    image: null,
    price_currency: "NGN",
    description: "Refreshing mango smoothie.",
    price: "NGN7000",
    stock_uom: "Unit",
    available_stock_quantity: 25,
    barcode: "smooth1234",
    userFav: false,
    userPined: true,
    valuation_rate: "750",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "10",
    warehouse: "obigbp",
  },
  {
    id: 7,
    name: "Chicken Sandwich",
    price_amount: "9000",
    image: null,
    price_currency: "NGN",
    description: "Savory chicken sandwich.",
    price: "NGN9000",
    stock_uom: "Unit",
    available_stock_quantity: 18,
    barcode: "sandwich4567",
    userFav: true,
    userPined: false,
    valuation_rate: "950",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "15",
    warehouse: "obigbp",
  },
  {
    id: 8,
    name: "Green Salad",
    price_amount: "4000",
    image: null,
    price_currency: "NGN",
    description: "Healthy green salad.",
    price: "NGN4000",
    stock_uom: "Unit",
    available_stock_quantity: 22,
    barcode: "salad7890",
    userFav: false,
    userPined: true,
    valuation_rate: "450",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "5",
    warehouse: "obigbp",
  },
  {
    id: 9,
    name: "Lemonade",
    price_amount: "3000",
    image: null,
    price_currency: "NGN",
    description: "Refreshing lemonade.",
    price: "NGN3000",
    stock_uom: "Unit",
    available_stock_quantity: 35,
    barcode: "lemon1234",
    userFav: true,
    userPined: false,
    valuation_rate: "350",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "8",
    warehouse: "obigbp",
  },

  {
    id: 10,
    name: "Pasta Alfredo",
    price_amount: "1500",
    image: null,
    price_currency: "NGN",
    description: "Creamy pasta Alfredo.",
    price: "NGN1500",
    stock_uom: "Unit",
    available_stock_quantity: 14,
    barcode: "pasta4567",
    userFav: false,
    userPined: true,
    valuation_rate: "1600",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "20",
    warehouse: "obigbp",
  },

  {
    id: 11,
    name: "Tuna Salad",
    price_amount: "7000",
    image: null,
    price_currency: "NGN",
    description: "Fresh tuna salad.",
    price: "NGN7000",
    stock_uom: "Unit",
    available_stock_quantity: 10,
    barcode: "tuna1234",
    userFav: true,
    userPined: false,
    valuation_rate: "750",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "12",
    warehouse: "obigbp",
  },
  {
    id: 12,
    name: "Iced Coffee",
    price_amount: "4500",
    image: null,
    price_currency: "NGN",
    description: "Iced coffee with cream.",
    price: "NGN4500",
    stock_uom: "Unit",
    available_stock_quantity: 20,
    barcode: "iced4567",
    userFav: false,
    userPined: true,
    valuation_rate: "500",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "10",
    warehouse: "obigbp",
  },
  {
    id: 13,
    name: "Chicken Noodle Soup",
    price_amount: "5500",
    image: null,
    price_currency: "NGN",
    description: "Warm chicken noodle soup.",
    price: "NGN5500",
    stock_uom: "Unit",
    available_stock_quantity: 15,
    barcode: "soup7890",
    userFav: true,
    userPined: false,
    valuation_rate: "600",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "8",
    warehouse: "obigbp",
  },
  {
    id: 14,
    name: "Fruit Platter",
    price_amount: "7500",
    image: null,
    price_currency: "NGN",
    description: "Assorted fruit platter.",
    price: "NGN7500",
    stock_uom: "Unit",
    available_stock_quantity: 25,
    barcode: "fruit1234",
    userFav: false,
    userPined: true,
    valuation_rate: "800",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "10",
    warehouse: "obigbp",
  },
  {
    id: 15,
    name: "Spaghetti Bolognese",
    price_amount: "1200",
    image: null,
    price_currency: "NGN",
    description: "Classic spaghetti Bolognese.",
    price: "NGN1200",
    stock_uom: "Unit",
    available_stock_quantity: 18,
    barcode: "spaghetti4567",
    userFav: true,
    userPined: false,
    valuation_rate: "1300",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "15",
    warehouse: "obigbp",
  },
  {
    id: 16,
    name: "Cucumber Salad",
    price_amount: "3500",
    image: null,
    price_currency: "NGN",
    description: "Refreshing cucumber salad.",
    price: "NGN3500",
    stock_uom: "Unit",
    available_stock_quantity: 22,
    barcode: "cucumber7890",
    userFav: false,
    userPined: true,
    valuation_rate: "400",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "5",
    warehouse: "obigbp",
  },
  {
    id: 17,
    name: "Orange Juice",
    price_amount: "3000",
    image: null,
    price_currency: "NGN",
    description: "Freshly squeezed orange juice.",
    price: "NGN3000",
    stock_uom: "Unit",
    available_stock_quantity: 30,
    barcode: "oj1234",
    userFav: true,
    userPined: false,
    valuation_rate: "350",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "8",
    warehouse: "obigbp",
  },
  {
    id: 18,
    name: "Beef Burger",
    price_amount: "9000",
    image: null,
    price_currency: "NGN",
    description: "Juicy beef burger.",
    price: "NGN9000",
    stock_uom: "Unit",
    available_stock_quantity: 14,
    barcode: "burger4567",
    userFav: false,
    userPined: true,
    valuation_rate: "950",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "12",
    warehouse: "obigbp",
  },
  {
    id: 19,
    name: "Fried Rice",
    price_amount: "1300",
    image: null,
    price_currency: "NGN",
    description: "Delicious fried rice.",
    price: "NGN1300",
    stock_uom: "Unit",
    available_stock_quantity: 20,
    barcode: "rice7890",
    userFav: true,
    userPined: false,
    valuation_rate: "1400",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "18",
    warehouse: "obigbp",
  },
  {
    id: 20,
    name: "Apple Pie",
    price_amount: "6000",
    image: null,
    price_currency: "NGN",
    description: "Homemade apple pie.",
    price: "NGN6000",
    stock_uom: "Unit",
    available_stock_quantity: 12,
    barcode: "apple1234",
    userFav: false,
    userPined: true,
    valuation_rate: "650",
    min_order_qty: 1,
    allow_negative_stock: false,
    tax: "10",
    warehouse: "obigbp",
  },
  {
    id: 21,
    name: "Caesar Salad",
    price_amount: "4500",
    image: null,
    price_currency: "NGN",
    description: "Classic Caesar salad.",
    price: "NGN4500",
    stock_uom: "Unit",
    available_stock_quantity: 18,
    barcode: "caesar4567",
    userFav: true,
    userPined: false,
    valuation_rate: "500",
    min_order_qty: 1,
    allow_negative_stock: true,
    tax: "8",
    warehouse: "obigbp",
  },
];
