export default  [
    {
        "id": 1,
        "name": "Chicken Lap",
        "price_amount": "2000",
        "image": null,
        "price_currency": "NGN",
        "description": "bla bla bla ba",
        "price": "NGN20000",
        "stock_uom": "Unit",
        "available_stock_quantity": 2,
        "barcode": "sfsjosjfosf9303",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 2,
        "name": "Beef Steak",
        "price_amount": "2500",
        "image": null,
        "price_currency": "NGN",
        "description": "Delicious beef steak.",
        "price": "NGN25000",
        "stock_uom": "Unit",
        "available_stock_quantity": 5,
        "barcode": "sdfjso2304jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 3,
        "name": "Pasta",
        "price_amount": "1500",
        "image": null,
        "price_currency": "NGN",
        "description": "Classic pasta dish.",
        "price": "NGN15000",
        "stock_uom": "Unit",
        "available_stock_quantity": 10,
        "barcode": "sdfjso3498jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 4,
        "name": "Salad",
        "price_amount": "1200",
        "image": null,
        "price_currency": "NGN",
        "description": "Fresh and healthy salad.",
        "price": "NGN12000",
        "stock_uom": "Unit",
        "available_stock_quantity": 8,
        "barcode": "sdfjso1256jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 5,
        "name": "Pizza",
        "price_amount": "1800",
        "image": null,
        "price_currency": "NGN",
        "description": "Delicious pizza with various toppings.",
        "price": "NGN18000",
        "stock_uom": "Unit",
        "available_stock_quantity": 15,
        "barcode": "sdfjso7890jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 6,
        "name": "Sushi",
        "price_amount": "3000",
        "image": null,
        "price_currency": "NGN",
        "description": "Fresh sushi rolls.",
        "price": "NGN30000",
        "stock_uom": "Unit",
        "available_stock_quantity": 3,
        "barcode": "sdfjso5678jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 7,
        "name": "Burger",
        "price_amount": "1600",
        "image": null,
        "price_currency": "NGN",
        "description": "Juicy burger with fries.",
        "price": "NGN16000",
        "stock_uom": "Unit",
        "available_stock_quantity": 7,
        "barcode": "sdfjso2345jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 8,
        "name": "Fish Fillet",
        "price_amount": "2200",
        "image": null,
        "price_currency": "NGN",
        "description": "Tender fish fillet.",
        "price": "NGN22000",
        "stock_uom": "Unit",
        "available_stock_quantity": 4,
        "barcode": "sdfjso4567jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 9,
        "name": "Vegetable Soup",
        "price_amount": "1300",
        "image": null,
        "price_currency": "NGN",
        "description": "Hearty vegetable soup.",
        "price": "NGN13000",
        "stock_uom": "Unit",
        "available_stock_quantity": 9,
        "barcode": "sdfjso6543jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 10,
        "name": "Ice Cream",
        "price_amount": "800",
        "image": null,
        "price_currency": "NGN",
        "description": "Creamy ice cream.",
        "price": "NGN8000",
        "stock_uom": "Unit",
        "available_stock_quantity": 12,
        "barcode": "sdfjso7890jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 11,
        "name": "Tacos",
        "price_amount": "1700",
        "image": null,
        "price_currency": "NGN",
        "description": "Tasty tacos.",
        "price": "NGN17000",
        "stock_uom": "Unit",
        "available_stock_quantity": 6,
        "barcode": "sdfjso1234jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 12,
        "name": "Fried Rice",
        "price_amount": "1900",
        "image": null,
        "price_currency": "NGN",
        "description": "Savory fried rice.",
        "price": "NGN19000",
        "stock_uom": "Unit",
        "available_stock_quantity": 11,
        "barcode": "sdfjso5678jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 13,
        "name": "Hot Dog",
        "price_amount": "1100",
        "image": null,
        "price_currency": "NGN",
        "description": "Classic hot dog.",
        "price": "NGN11000",
        "stock_uom": "Unit",
        "available_stock_quantity": 7,
        "barcode": "sdfjso2345jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 14,
        "name": "Fried Chicken",
        "price_amount": "2100",
        "image": null,
        "price_currency": "NGN",
        "description": "Crispy fried chicken.",
        "price": "NGN21000",
        "stock_uom": "Unit",
        "available_stock_quantity": 5,
        "barcode": "sdfjso4567jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 15,
        "name": "Mango Smoothie",
        "price_amount": "900",
        "image": null,
        "price_currency": "NGN",
        "description": "Refreshing mango smoothie.",
        "price": "NGN9000",
        "stock_uom": "Unit",
        "available_stock_quantity": 9,
        "barcode": "sdfjso6543jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 16,
        "name": "Caesar Salad",
        "price_amount": "1400",
        "image": null,
        "price_currency": "NGN",
        "description": "Classic Caesar salad.",
        "price": "NGN14000",
        "stock_uom": "Unit",
        "available_stock_quantity": 8,
        "barcode": "sdfjso7890jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 17,
        "name": "Shrimp Scampi",
        "price_amount": "2600",
        "image": null,
        "price_currency": "NGN",
        "description": "Scrumptious shrimp scampi.",
        "price": "NGN26000",
        "stock_uom": "Unit",
        "available_stock_quantity": 3,
        "barcode": "sdfjso5678jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 18,
        "name": "Crispy Tofu",
        "price_amount": "1700",
        "image": null,
        "price_currency": "NGN",
        "description": "Crispy tofu bites.",
        "price": "NGN17000",
        "stock_uom": "Unit",
        "available_stock_quantity": 6,
        "barcode": "sdfjso1234jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 19,
        "name": "Lobster Tail",
        "price_amount": "3200",
        "image": null,
        "price_currency": "NGN",
        "description": "Deluxe lobster tail.",
        "price": "NGN32000",
        "stock_uom": "Unit",
        "available_stock_quantity": 2,
        "barcode": "sdfjso2345jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 20,
        "name": "Chocolate Cake",
        "price_amount": "1800",
        "image": null,
        "price_currency": "NGN",
        "description": "Decadent chocolate cake.",
        "price": "NGN18000",
        "stock_uom": "Unit",
        "available_stock_quantity": 10,
        "barcode": "sdfjso4567jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 21,
        "name": "Vegetable Stir Fry",
        "price_amount": "1500",
        "image": null,
        "price_currency": "NGN",
        "description": "Sizzling vegetable stir fry.",
        "price": "NGN15000",
        "stock_uom": "Unit",
        "available_stock_quantity": 8,
        "barcode": "sdfjso6543jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 22,
        "name": "Fruit Salad",
        "price_amount": "1200",
        "image": null,
        "price_currency": "NGN",
        "description": "Fresh fruit salad.",
        "price": "NGN12000",
        "stock_uom": "Unit",
        "available_stock_quantity": 12,
        "barcode": "sdfjso7890jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 23,
        "name": "BBQ Ribs",
        "price_amount": "2800",
        "image": null,
        "price_currency": "NGN",
        "description": "Tender BBQ ribs.",
        "price": "NGN28000",
        "stock_uom": "Unit",
        "available_stock_quantity": 5,
        "barcode": "sdfjso5678jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 24,
        "name": "Mushroom Risotto",
        "price_amount": "1900",
        "image": null,
        "price_currency": "NGN",
        "description": "Creamy mushroom risotto.",
        "price": "NGN19000",
        "stock_uom": "Unit",
        "available_stock_quantity": 9,
        "barcode": "sdfjso2345jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 25,
        "name": "Blueberry Pancakes",
        "price_amount": "1100",
        "image": null,
        "price_currency": "NGN",
        "description": "Fluffy blueberry pancakes.",
        "price": "NGN11000",
        "stock_uom": "Unit",
        "available_stock_quantity": 7,
        "barcode": "sdfjso4567jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 26,
        "name": "Grilled Salmon",
        "price_amount": "2400",
        "image": null,
        "price_currency": "NGN",
        "description": "Grilled salmon fillet.",
        "price": "NGN24000",
        "stock_uom": "Unit",
        "available_stock_quantity": 4,
        "barcode": "sdfjso6543jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 27,
        "name": "Spaghetti Carbonara",
        "price_amount": "1600",
        "image": null,
        "price_currency": "NGN",
        "description": "Creamy spaghetti carbonara.",
        "price": "NGN16000",
        "stock_uom": "Unit",
        "available_stock_quantity": 8,
        "barcode": "sdfjso7890jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 28,
        "name": "Tiramisu",
        "price_amount": "1200",
        "image": null,
        "price_currency": "NGN",
        "description": "Classic Italian tiramisu.",
        "price": "NGN12000",
        "stock_uom": "Unit",
        "available_stock_quantity": 10,
        "barcode": "sdfjso5678jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 29,
        "name": "Cobb Salad",
        "price_amount": "1400",
        "image": null,
        "price_currency": "NGN",
        "description": "Fresh Cobb salad.",
        "price": "NGN14000",
        "stock_uom": "Unit",
        "available_stock_quantity": 7,
        "barcode": "sdfjso1234jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 30,
        "name": "Fajitas",
        "price_amount": "1800",
        "image": null,
        "price_currency": "NGN",
        "description": "Sizzling fajitas.",
        "price": "NGN18000",
        "stock_uom": "Unit",
        "available_stock_quantity": 6,
        "barcode": "sdfjso2345jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 31,
        "name": "Lemonade",
        "price_amount": "600",
        "image": null,
        "price_currency": "NGN",
        "description": "Refreshing lemonade.",
        "price": "NGN6000",
        "stock_uom": "Unit",
        "available_stock_quantity": 15,
        "barcode": "sdfjso7890jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 32,
        "name": "Hamburger",
        "price_amount": "1600",
        "image": null,
        "price_currency": "NGN",
        "description": "Classic hamburger.",
        "price": "NGN16000",
        "stock_uom": "Unit",
        "available_stock_quantity": 7,
        "barcode": "sdfjso4567jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 33,
        "name": "Fried Shrimp",
        "price_amount": "2100",
        "image": null,
        "price_currency": "NGN",
        "description": "Crispy fried shrimp.",
        "price": "NGN21000",
        "stock_uom": "Unit",
        "available_stock_quantity": 5,
        "barcode": "sdfjso6543jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 34,
        "name": "Miso Soup",
        "price_amount": "900",
        "image": null,
        "price_currency": "NGN",
        "description": "Traditional miso soup.",
        "price": "NGN9000",
        "stock_uom": "Unit",
        "available_stock_quantity": 10,
        "barcode": "sdfjso2345jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 35,
        "name": "Nachos",
        "price_amount": "1400",
        "image": null,
        "price_currency": "NGN",
        "description": "Cheesy nachos with salsa.",
        "price": "NGN14000",
        "stock_uom": "Unit",
        "available_stock_quantity": 8,
        "barcode": "sdfjso5678jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 36,
        "name": "Steak Frites",
        "price_amount": "2500",
        "image": null,
        "price_currency": "NGN",
        "description": "Savory steak frites.",
        "price": "NGN25000",
        "stock_uom": "Unit",
        "available_stock_quantity": 4,
        "barcode": "sdfjso1234jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 37,
        "name": "Sushi Platter",
        "price_amount": "3500",
        "image": null,
        "price_currency": "NGN",
        "description": "Assorted sushi platter.",
        "price": "NGN35000",
        "stock_uom": "Unit",
        "available_stock_quantity": 3,
        "barcode": "sdfjso7890jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 38,
        "name": "Chicken Curry",
        "price_amount": "1800",
        "image": null,
        "price_currency": "NGN",
        "description": "Spicy chicken curry.",
        "price": "NGN18000",
        "stock_uom": "Unit",
        "available_stock_quantity": 6,
        "barcode": "sdfjso5678jsf",
        "userFav": true,
        "userPined": false
    },
    {
        "id": 39,
        "name": "Crispy Bacon",
        "price_amount": "1200",
        "image": null,
        "price_currency": "NGN",
        "description": "Extra crispy bacon.",
        "price": "NGN12000",
        "stock_uom": "Unit",
        "available_stock_quantity": 9,
        "barcode": "sdfjso2345jsf",
        "userFav": false,
        "userPined": true
    },
    {
        "id": 40,
        "name": "Strawberry Cheesecake",
        "price_amount": "1600",
        "image": null,
        "price_currency": "NGN",
        "description": "Creamy strawberry cheesecake.",
        "price": "NGN160000000",
        "stock_uom": "Unit",
        "available_stock_quantity": 7,
        "barcode": "sdfjso4567jsf",
        "userFav": true,
        "userPined": false
    }]

